// GENERATED by handheld/tools/gen_rules.mjs from arcade/src/data/rules.mjs. Do not edit.
// rules.mjs sha256 6484d5dcfded4db34d4bbee7229252ed620afeb0efb4c5b0882d6d6c62108d89
#pragma once
#include <stdint.h>

#define STR_SIM_AIR_ACCEL 15
#define STR_SIM_AIR_DRAG 2
#define STR_SIM_FLAP_IMPULSE_SUBPX_PER_TICK 333
#define STR_SIM_FLAP_VY_CLAMP (-640)
#define STR_SIM_GRAVITY_SUBPX_PER_TICK2 21
#define STR_SIM_GROUND_ACCEL 18
#define STR_SIM_GROUND_FRICTION 14
#define STR_SIM_HEAD_BUMP_VY 196
#define STR_SIM_INPUT_FLAP_QUEUE_MAX 4
#define STR_SIM_LANCE_BOUNCE_VX 265
#define STR_SIM_LANCE_BOUNCE_VY (-111)
#define STR_SIM_LANCE_TIE_BAND_SUBPX 512
#define STR_SIM_LAVA_INVULNERABLE_TICKS 54
#define STR_SIM_LAVA_RESCUE_VY (-563)
#define STR_SIM_LAVA_RESCUE_WINDOW_TICKS 18
#define STR_SIM_LAVA_Y 352
#define STR_SIM_MAX_AIR_SPEED 444
#define STR_SIM_MAX_FALL 896
#define STR_SIM_MAX_GROUND_SPEED 393
#define STR_SIM_PLAY_TOP 20
#define STR_SIM_PLAYER_GRACE_SUBPX 640
#define STR_SIM_SKID_DECEL 31
#define STR_SIM_SPAWN_SHIMMER_TICKS 150
#define STR_SIM_STALL_HUNT_TICKS 1200
#define STR_SIM_SUBPIXELS_PER_PIXEL 256
#define STR_SIM_TICK_HZ 60
#define STR_SIM_WALL_BOUNCE_DENOMINATOR 100
#define STR_SIM_WALL_BOUNCE_NUMERATOR (-45)
#define STR_SIM_WING_MAX 64
#define STR_SIM_WING_RECHARGE_ARM_TICKS 12
#define STR_SIM_WING_RECHARGE_INTERVAL_TICKS 3
#define STR_LIFECYCLE_DISMOUNT_MINIMUM 30
#define STR_LIFECYCLE_EGG 360
#define STR_LIFECYCLE_HATCHING 60
#define STR_LIFECYCLE_REMOUNTING 90
#define STR_SCORING_FIRST_LIFE 30000
#define STR_SCORING_JOUST_TIER_STEP 250
#define STR_SCORING_LIFE_EVERY 100000
#define STR_SCORING_MAX_LIVES 11
#define STR_SCORING_RING 500
#define STR_SCORING_ROUND_CLEAR_BASE 5000
#define STR_SCORING_ROUND_CLEAR_MAX 15000
#define STR_SCORING_ROUND_CLEAR_STEP 1000
#define STR_SCORING_START_LIVES 11
#define STR_SCORING_SURVIVAL 3000
#define STR_SCORING_EGG_CHAIN_0 250
#define STR_SCORING_EGG_CHAIN_1 500
#define STR_SCORING_EGG_CHAIN_2 750
#define STR_SCORING_EGG_CHAIN_3 1000
#define STR_SCORING_JOUST_BOUNDER 500
#define STR_SCORING_JOUST_HUNTER 750
#define STR_SCORING_JOUST_SHADOW 1000
#define STR_INPUT_CHORD_WINDOW_MS 100
#define STR_INPUT_FLAP_BUFFER_TICKS 8
#define STR_INPUT_DART_ANGLE_DEGREES 35

// Palette (RGB565), in rules.mjs order.
enum {
    STR_PAL_BLACK = 0,
    STR_PAL_CHROME = 1,
    STR_PAL_CHROME_DARK = 2,
    STR_PAL_CHROME_LIGHT = 3,
    STR_PAL_CYAN = 4,
    STR_PAL_CYAN_DARK = 5,
    STR_PAL_CYAN_DEEP = 6,
    STR_PAL_CYAN_LIGHT = 7,
    STR_PAL_EARTH = 8,
    STR_PAL_EARTH_DARK = 9,
    STR_PAL_EARTH_LIGHT = 10,
    STR_PAL_EMBER = 11,
    STR_PAL_GOLD = 12,
    STR_PAL_GOLD_DEEP = 13,
    STR_PAL_GOLD_LIGHT = 14,
    STR_PAL_GREEN = 15,
    STR_PAL_INK = 16,
    STR_PAL_IVORY = 17,
    STR_PAL_IVORY_DARK = 18,
    STR_PAL_IVORY_LIGHT = 19,
    STR_PAL_KINGDOM_CRIMSON_LIGHT = 20,
    STR_PAL_KINGDOM_GOLD = 21,
    STR_PAL_KINGDOM_GOLD_LIGHT = 22,
    STR_PAL_LAVA = 23,
    STR_PAL_LAVA_HOT = 24,
    STR_PAL_NAVY = 25,
    STR_PAL_NAVY_SOFT = 26,
    STR_PAL_OCHRE = 27,
    STR_PAL_RING = 28,
    STR_PAL_RING_DARK = 29,
    STR_PAL_RING_DEEP = 30,
    STR_PAL_RING_LIGHT = 31,
    STR_PAL_VOID = 32,
    STR_PAL_VOID_DEEP = 33,
    STR_PAL_WHITE = 34,
    STR_PAL_COUNT = 35
};
static const uint16_t STR_PALETTE_RGB565[STR_PAL_COUNT] = {
    0x0000, /* black #000000 */
    0xe75d, /* chrome #E5E9EC */
    0x638f, /* chromeDark #62717B */
    0xf7bd, /* chromeLight #F3F4EC */
    0x263a, /* cyan #20C4D7 */
    0x0b4e, /* cyanDark #0D6875 */
    0x09c8, /* cyanDeep #083A44 */
    0x7f7f, /* cyanLight #7BEFFF */
    0x6245, /* earth #67482F */
    0x28c2, /* earthDark #2A1914 */
    0x9b48, /* earthLight #9B6841 */
    0xfce7, /* ember #FF9D3B */
    0xe547, /* gold #E2A93F */
    0x4961, /* goldDeep #4A2E08 */
    0xfead, /* goldLight #FFD56A */
    0x4eb1, /* green #48D78A */
    0x0841, /* ink #090A0B */
    0xde96, /* ivory #DED2B4 */
    0xacf0, /* ivoryDark #AC9F84 */
    0xf77a, /* ivoryLight #F6ECD4 */
    0xf244, /* kingdomCrimsonLight #F24A22 */
    0xe547, /* kingdomGold #E2A93F */
    0xfead, /* kingdomGoldLight #FFD56A */
    0xb8e3, /* lava #B91E18 */
    0xf244, /* lavaHot #F24A22 */
    0x1147, /* navy #102838 */
    0x11c8, /* navySoft #173A46 */
    0xd4a8, /* ochre #D69543 */
    0x263a, /* ring #20C4D7 */
    0x0b4e, /* ringDark #0D6875 */
    0x09c8, /* ringDeep #083A44 */
    0x7f7f, /* ringLight #7BEFFF */
    0x0083, /* void #07131F */
    0x0020, /* voidDeep #020406 */
    0xfffe, /* white #FFFDF3 */
};

// 5x7 font: 7 rows per glyph, bit 4 is the leftmost column.
typedef struct { char ch; uint8_t rows[7]; } str_glyph_t;
static const str_glyph_t STR_FONT_5X7[] = {
    {'0', {14, 17, 19, 21, 25, 17, 14}},
    {'1', {4, 12, 4, 4, 4, 4, 14}},
    {'2', {14, 17, 1, 2, 4, 8, 31}},
    {'3', {30, 1, 1, 14, 1, 1, 30}},
    {'4', {2, 6, 10, 18, 31, 2, 2}},
    {'5', {31, 16, 16, 30, 1, 1, 30}},
    {'6', {14, 16, 16, 30, 17, 17, 14}},
    {'7', {31, 1, 2, 4, 8, 8, 8}},
    {'8', {14, 17, 17, 14, 17, 17, 14}},
    {'9', {14, 17, 17, 15, 1, 1, 14}},
    {' ', {0, 0, 0, 0, 0, 0, 0}},
    {'!', {4, 4, 4, 4, 4, 0, 4}},
    {'\'', {4, 4, 8, 0, 0, 0, 0}},
    {'(', {2, 4, 8, 8, 8, 4, 2}},
    {')', {8, 4, 2, 2, 2, 4, 8}},
    {'+', {0, 4, 4, 31, 4, 4, 0}},
    {',', {0, 0, 0, 0, 0, 12, 8}},
    {'-', {0, 0, 0, 31, 0, 0, 0}},
    {'.', {0, 0, 0, 0, 0, 12, 12}},
    {'/', {1, 2, 2, 4, 8, 8, 16}},
    {':', {0, 12, 12, 0, 12, 12, 0}},
    {';', {0, 12, 12, 0, 12, 8, 0}},
    {'?', {14, 17, 1, 2, 4, 0, 4}},
    {'A', {14, 17, 17, 31, 17, 17, 17}},
    {'B', {30, 17, 17, 30, 17, 17, 30}},
    {'C', {14, 17, 16, 16, 16, 17, 14}},
    {'D', {30, 17, 17, 17, 17, 17, 30}},
    {'E', {31, 16, 16, 30, 16, 16, 31}},
    {'F', {31, 16, 16, 30, 16, 16, 16}},
    {'G', {14, 17, 16, 23, 17, 17, 15}},
    {'H', {17, 17, 17, 31, 17, 17, 17}},
    {'I', {14, 4, 4, 4, 4, 4, 14}},
    {'J', {7, 2, 2, 2, 2, 18, 12}},
    {'K', {17, 18, 20, 24, 20, 18, 17}},
    {'L', {16, 16, 16, 16, 16, 16, 31}},
    {'M', {17, 27, 21, 21, 17, 17, 17}},
    {'N', {17, 25, 21, 19, 17, 17, 17}},
    {'O', {14, 17, 17, 17, 17, 17, 14}},
    {'P', {30, 17, 17, 30, 16, 16, 16}},
    {'Q', {14, 17, 17, 17, 21, 18, 13}},
    {'R', {30, 17, 17, 30, 20, 18, 17}},
    {'S', {15, 16, 16, 14, 1, 1, 30}},
    {'T', {31, 4, 4, 4, 4, 4, 4}},
    {'U', {17, 17, 17, 17, 17, 17, 14}},
    {'V', {17, 17, 17, 17, 17, 10, 4}},
    {'W', {17, 17, 17, 21, 21, 21, 10}},
    {'X', {17, 17, 10, 4, 10, 17, 17}},
    {'Y', {17, 17, 10, 4, 4, 4, 4}},
    {'Z', {31, 1, 2, 4, 8, 16, 31}},
    {'[', {14, 8, 8, 8, 8, 8, 14}},
    {']', {14, 2, 2, 2, 2, 2, 14}},
};
enum { STR_FONT_GLYPHS = 51 };
