#!/usr/bin/env python3
"""STRUTHIO ARCADE release build.

    python3 tools/build.py      -> refreshes sw.js and SHA256SUMS.txt, writes dist/STRUTHIO_ARCADE_<ver>.zip

Ships index.html, manifest, _headers, sw.js, assets/ and src/. tests/, tools/,
README.md and dist/ stay out of the release.
"""
import hashlib, json, re, zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BUILD = re.search(r"BUILD_ID='STRUTHIO-ARCADE-([^']+)'", (ROOT / 'src/app/boot.mjs').read_text()).group(1)
SHIP = ['index.html', 'manifest.webmanifest', '_headers']
SHIP_DIRS = ['assets', 'src']

SW = r"""// STRUTHIO ARCADE service worker: precache every file of the build, then
// serve them offline. Generated by tools/build.py; do not edit the list.
// Safari refuses a service-worker response that went through a redirect (hosts
// such as Cloudflare Pages and Netlify redirect /index.html to /), so every
// response is stored and served "clean", and pages load network-first.
const BUILD='STRUTHIO-ARCADE-__BUILD__';
const CACHE=`struthio-arcade-${BUILD}`;
const CORE=__CORE__;
const clean=async(r)=>r.redirected?new Response(await r.blob(),{status:r.status,statusText:r.statusText,headers:r.headers}):r;
self.addEventListener('install',(event)=>event.waitUntil((async()=>{
const cache=await caches.open(CACHE);
try{for (const url of CORE){const r=await fetch(url,{cache:'reload'});if (!r.ok) throw new Error(`precache ${url} ${r.status}`);await cache.put(url,await clean(r));}}
catch (error){await caches.delete(CACHE);throw error;}
// Take over at once: a broken older worker must never keep the page from loading.
await self.skipWaiting();
})()));
self.addEventListener('activate',(event)=>event.waitUntil((async()=>{
for (const name of await caches.keys()) if (name!==CACHE&&name.startsWith('struthio-arcade-')) await caches.delete(name);
await self.clients.claim();
})()));
self.addEventListener('message',(event)=>{if (event.data?.type==='SKIP_WAITING') self.skipWaiting();});
const offlinePage=async(cache)=>{const hit=(await cache.match('./'))||(await cache.match('./index.html'));return hit?clean(hit):Response.error();};
self.addEventListener('fetch',(event)=>{
if (event.request.method!=='GET'||new URL(event.request.url).origin!==location.origin) return;
event.respondWith((async()=>{
const cache=await caches.open(CACHE);
if (event.request.mode==='navigate'){
// Network first (the browser follows any redirect itself); the cached page
// only when offline or the network takes longer than 4 s.
const net=fetch(event.request);
const timeout=new Promise((resolve)=>setTimeout(()=>resolve(null),4000));
try{const r=await Promise.race([net,timeout]);if (r) return r;}catch{return offlinePage(cache);}
return offlinePage(cache);
}
let hit=await cache.match(event.request,{ignoreSearch:true});
if (hit){
hit=await clean(hit);
const range=event.request.headers.get('range');
if (!range) return hit;
const body=await hit.arrayBuffer(),m=/bytes=(\d*)-(\d*)/.exec(range)||[];
const start=Number(m[1]||0),end=m[2]?Math.min(Number(m[2]),body.byteLength-1):body.byteLength-1;
return new Response(body.slice(start,end+1),{status:206,headers:{'content-type':hit.headers.get('content-type')||'application/octet-stream','content-range':`bytes ${start}-${end}/${body.byteLength}`,'accept-ranges':'bytes'}});
}
const response=await fetch(event.request);
if (response.ok&&response.status===200&&!response.redirected) cache.put(event.request,response.clone()).catch(()=>{});
return response;
})());
});
"""

def shipped():
    files = [f for f in SHIP]
    for d in SHIP_DIRS:
        files += sorted(p.relative_to(ROOT).as_posix() for p in (ROOT / d).rglob('*') if p.is_file())
    return files

def main():
    core = ['./'] + ['./' + f for f in shipped() if f != '_headers']
    (ROOT / 'sw.js').write_text(SW.replace('__BUILD__', BUILD).replace('__CORE__', json.dumps(core)))
    files = sorted(set(shipped() + ['sw.js']))
    (ROOT / 'SHA256SUMS.txt').write_text(''.join(f'{hashlib.sha256((ROOT / f).read_bytes()).hexdigest()}  {f}\n' for f in files))
    out = ROOT / 'dist' / f'STRUTHIO_ARCADE_{BUILD}.zip'
    out.parent.mkdir(exist_ok=True)
    with zipfile.ZipFile(out, 'w', zipfile.ZIP_DEFLATED) as z:
        for f in ['SHA256SUMS.txt'] + files:
            info = zipfile.ZipInfo(f, date_time=(2026, 1, 1, 0, 0, 0))
            info.compress_type = zipfile.ZIP_STORED if f.endswith(('.webp', '.png', '.jpg', '.mp3')) else zipfile.ZIP_DEFLATED
            info.external_attr = 0o644 << 16
            z.writestr(info, (ROOT / f).read_bytes())
    size = sum((ROOT / f).stat().st_size for f in files)
    print(f'STRUTHIO-ARCADE-{BUILD}: {len(files) + 1} files, {size / 1e6:.2f} MB -> {out.relative_to(ROOT)}')

if __name__ == '__main__':
    main()
