// GENERATED by handheld/tools/gen_audio.mjs. Do not edit.
// rules.mjs     sha256 6484d5dcfded4db34d4bbee7229252ed620afeb0efb4c5b0882d6d6c62108d89
// conductor.mjs sha256 9d321ba6aeafd6ce7ade78946e2f1c3787f031550d8bc9f9b723bf9ad41b9117
// synth.mjs     sha256 135af4fd2da2e6d6d65a84fcf7317f99a85465f9e677abdbef754c576bddc592
// session.mjs   sha256 0b11c6e20e8bf60f641883e2c51c502864867de800f9c086d98bca9e4cc4aa5c
#pragma once
#include <stdint.h>
#include "struthio_core.h"

#define STA_SAMPLE_RATE 48000
#define STA_TRANSPORT_BPM_Q16 6271999
#define STA_BEATS_PER_BAR 4
// buses, after synthConfig (the SFX bus is scaled by 0.71 there)
#define STA_MASTER_GAIN_Q15 26214
#define STA_MUSIC_GAIN_Q15 19661
#define STA_SFX_GAIN_Q15 17449
#define STA_LIMITER_CEILING_Q15 31129
#define STA_DC_BLOCK_R_Q15 32604
#define STA_TRANSIENT_POOL_CAP 32
#define STA_SUSTAINED_VOICE_CAP 10
// the WebAudio graph after the synth (session.mjs)
#define STA_SFX_NODE_GAIN 0.68f
#define STA_MASTER_NODE_GAIN 0.92f
#define STA_COMP_THRESHOLD_DB -12.0f
#define STA_COMP_KNEE_DB 12.0f
#define STA_COMP_RATIO 8.0f
#define STA_COMP_ATTACK_S 0.003f
#define STA_COMP_RELEASE_S 0.25f
#define STA_MUSIC_GAIN 0.56f

typedef enum { STA_WAVE_SINE, STA_WAVE_TRIANGLE, STA_WAVE_SAW, STA_WAVE_PULSE_50, STA_WAVE_PULSE_25, STA_WAVE_PULSE_12_5, STA_WAVE_XORSHIFT_NOISE } sta_wave_t;
typedef enum { STA_FILTER_LP1, STA_FILTER_HP1 } sta_filter_t;
typedef struct { const char *id; uint8_t wave, filter; int32_t coef_q15, attack, decay, sustain_q15, release, gain_q15, glide; } sta_voice_t;
enum { STA_VOICE_COUNT = 7 };
static const sta_voice_t STA_VOICES[STA_VOICE_COUNT] = {
    {"C_FLAP", STA_WAVE_XORSHIFT_NOISE, STA_FILTER_LP1, 5200, 72, 1300, 0, 900, 10400, -7},
    {"C_RING", STA_WAVE_SINE, STA_FILTER_LP1, 30000, 60, 5200, 6000, 5600, 8600, 5},
    {"C_CLASH", STA_WAVE_XORSHIFT_NOISE, STA_FILTER_LP1, 2600, 24, 2200, 0, 700, 9800, -12},
    {"C_WIN", STA_WAVE_TRIANGLE, STA_FILTER_LP1, 20000, 60, 5400, 7000, 6000, 9000, 7},
    {"C_DEATH", STA_WAVE_TRIANGLE, STA_FILTER_LP1, 9000, 120, 9000, 4000, 7200, 9800, -19},
    {"C_PLINK", STA_WAVE_SINE, STA_FILTER_LP1, 30000, 48, 2600, 0, 1800, 6200, 3},
    {"C_STING", STA_WAVE_PULSE_25, STA_FILTER_LP1, 7000, 240, 7200, 9000, 9600, 6200, 0},
};

typedef enum { STA_Q_NONE = 0, STA_Q_NEXT_EIGHTH = 1, STA_Q_NEXT_BEAT = 2 } sta_quantize_t;
// one row per SFX: voice, MIDI note, gate length (s), pitch jitter (semitones),
// minimum gap (s, 0 = none), priority and quantize (rules.mjs eventMap), protected
typedef struct { const char *key; uint8_t voice; int16_t midi; float len; int8_t jitter; float min_gap; uint8_t priority, quantize, protected_note; } sta_sfx_t;
enum { STA_SFX_COUNT = 9 };
static const sta_sfx_t STA_SFX[STA_SFX_COUNT] = {
    {"flap", 0, 84, 0.05f, 2, 0.085f, 2, 0, 0},
    {"ring", 1, 81, 0.16f, 0, 0.0f, 4, 0, 0},
    {"joust-clash", 2, 52, 0.07f, 1, 0.0f, 9, 0, 0},
    {"joust-win", 3, 76, 0.22f, 0, 0.0f, 10, 0, 1},
    {"player-death", 4, 60, 0.42f, 0, 0.0f, 10, 0, 1},
    {"egg", 5, 79, 0.08f, 1, 0.0f, 3, 0, 0},
    {"hatch", 5, 72, 0.14f, 1, 0.0f, 5, 0, 0},
    {"gold-open", 6, 76, 0.45f, 0, 0.0f, 8, 2, 1},
    {"round-clear", 6, 84, 0.8f, 0, 0.0f, 10, 2, 1},
};
// game event -> SFX row (-1: silent)
static inline int sta_sfx_for_event(int type) {
    switch (type) {
    case ST_EV_FLAP: return 0;   // flap
    case ST_EV_RING: return 1;   // ring
    case ST_EV_JOUST_CLASH: return 2;   // joust-clash
    case ST_EV_JOUST_WIN: return 3;   // joust-win
    case ST_EV_PLAYER_DEATH: return 4;   // player-death
    case ST_EV_EGG: return 5;   // egg
    case ST_EV_HATCH: return 6;   // hatch
    case ST_EV_GOLD_RING_OPEN: return 7;   // gold-open
    case ST_EV_ROUND_START: return 7;   // gold-open
    case ST_EV_ROUND_CLEAR: return 8;   // round-clear
    default: return -1;
    }
}

// music ducks (session.mjs): volume x (1 - (1 - depth) x 0.5) for attack + hold + release seconds
typedef struct { uint8_t event; uint8_t player_only; float depth, attack, hold, release; } sta_duck_t;
enum { STA_DUCK_COUNT = 5 };
static const sta_duck_t STA_DUCKS[STA_DUCK_COUNT] = {
    {ST_EV_ROUND_CLEAR, 0, 0.35f, 0.004f, 0.08f, 0.5f},
    {ST_EV_RING, 0, 0.82f, 0.006f, 0.012f, 0.11f},
    {ST_EV_JOUST_CLASH, 1, 0.68f, 0.004f, 0.018f, 0.14f},
    {ST_EV_JOUST_WIN, 0, 0.42f, 0.004f, 0.035f, 0.24f},
    {ST_EV_PLAYER_DEATH, 0, 0.3f, 0.006f, 0.06f, 0.38f},
};
