// STRUTHIO HANDHELD · generates render/struthio_scene_data.c from the metadata
// the reference capture exported from the browser (atlas swatches, the font
// layout, island masters, the tower's island plans and baked atlas slots).
//   node handheld/tools/reference/capture.mjs --textures mortal
//   node handheld/tools/gen_scene_data.mjs
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { TOWER_PLATFORMS } from '../../arcade/src/sim/tower.mjs';
const here = path.dirname(fileURLToPath(import.meta.url));
const meta = JSON.parse(fs.readFileSync(path.join(here, '..', 'build', 'reference', 'textures', 'metadata.json'), 'utf8'));
const num = (v) => (Number.isInteger(v) ? String(v) : v.toPrecision(17));
const swatches = Object.entries(meta.swatch);
const masterIndex = new Map(meta.masters.map((m, i) => [m.id, i]));
const plans = new Map(meta.plans.map((p) => [p.id, p]));
const slots = new Map(meta.slots.map((s) => [s.id, s]));
const font = meta.fontIndex.map(([c]) => c);
const cstr = (c) => (c === '\\' ? "'\\\\'" : c === "'" ? "'\\''" : `'${c}'`);
const src = `// GENERATED by handheld/tools/gen_scene_data.mjs from the browser's own atlas
// metadata (handheld/tools/reference). Do not edit.
#include "struthio_scene.h"

const st_swatch_t ST_SWATCHES[ST_SWATCH_COUNT] = {
${swatches.map(([n, [x, y]]) => `    {"${n}", ${x}, ${y}},`).join('\n')}
};

// Font glyph order (Object.keys(font_5x7).sort()); the modern font cell grid.
const char ST_FONT_CHARS[ST_FONT_COUNT] = {${font.map(cstr).join(', ')}};
const st_modern_font_t ST_MODERN_FONT = {${['x', 'y', 'cols', 'cellW', 'cellH', 'rows', 'glyphW', 'glyphH'].map((k) => meta.modernFont[k]).join(', ')}};

const int ST_ISLANDS_ORIGIN[2] = {${meta.islandsOrigin.join(', ')}};
// id, x, y, w, h, capTop, topDecor
const st_island_master_t ST_ISLAND_MASTERS[ST_ISLAND_MASTER_COUNT] = {
${meta.masters.map((m) => `    {"${m.id}", ${m.x}, ${m.y}, ${m.w}, ${m.h}, ${m.capTop}, ${m.topDecor}},`).join('\n')}
};

// Per tower platform (ST_TOWER order): master, mirror, ground, depth (the
// browser's buildIslandLayout at scaleY 2), and its baked atlas slot if any.
const st_island_plan_t ST_ISLAND_PLANS[ST_TOWER_PLATFORMS] = {
${TOWER_PLATFORMS.map((p) => {
  const plan = plans.get(p.id), slot = slots.get(p.id);
  if (!plan) throw new Error('no plan for ' + p.id);
  return `    {${masterIndex.get(plan.master)}, ${plan.mirror ? 1 : 0}, ${plan.ground ? 1 : 0}, ${num(plan.depth)}, ${slot ? 1 : 0}, {${slot ? [slot.x, slot.y, slot.w, slot.h, slot.decorY, slot.decorH].join(', ') : '0, 0, 0, 0, 0, 0'}}}, /* ${p.id} */`;
}).join('\n')}
};
`;
if (swatches.length !== 41) console.log('note: swatch count', swatches.length);
fs.writeFileSync(path.join(here, '..', 'render', 'struthio_scene_data.c'), src);
console.log(`wrote render/struthio_scene_data.c (${swatches.length} swatches, ${font.length} glyphs, ${meta.masters.length} masters, ${slots.size} baked slots)`);
