// STRUTHIO HANDHELD · generates core/struthio_tower.c from the arcade's tower
// (arcade/src/sim/tower.mjs). Never hand-edit the output; re-run this instead:
//   node handheld/tools/gen_tower.mjs
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import * as T from '../../arcade/src/sim/tower.mjs';
const here = path.dirname(fileURLToPath(import.meta.url));
const out = path.join(here, '..', 'core', 'struthio_tower.c');
const MOTION = { DRIFT_X_SOFT: 'ST_MOTION_DRIFT_X_SOFT', BOB_Y_SOFT: 'ST_MOTION_BOB_Y_SOFT' };
const rows = T.TOWER_PLATFORMS.map((p) => {
  const m = typeof p.motion === 'object' ? p.motion : null;
  if (m && (m.dwell | 0) !== 0) throw new Error(`${p.id}: dwell not supported by the C port`);
  const look = p.look ? Number(p.look.replace('STD_', '')) : 0;
  return `    {"${p.id}", ${p.rect.join(', ')}, ${m ? MOTION[m.profile] : 'ST_MOTION_STATIC'}, ${m ? m.amplitude : 0}, ${m ? m.period : 0}, ${p.phaseOffset || 0}, ${look}, ${p.mirror ? 'true' : 'false'}},`;
});
if (T.TOWER_PLATFORMS.length !== 43) throw new Error('platform count changed: update ST_TOWER_PLATFORMS');
const ring = (r) => `{${r.center[0]}, ${r.center[1]}, ${r.radius}}`;
const src = `// GENERATED by handheld/tools/gen_tower.mjs from arcade/src/sim/tower.mjs. Do not edit.
#include "struthio_core.h"

// id, x, y, w, h, motion, amplitude, period, phase offset, island art, mirrored
const st_tower_platform_t ST_TOWER[ST_TOWER_PLATFORMS] = {
${rows.join('\n')}
};

const st_ring_t ST_RING_SET[ST_RING_SETS][ST_RINGS_PER_SET] = {
${T.RING_SETS.map((set) => `    {${set.map(ring).join(', ')}},`).join('\n')}
};

const st_ring_t ST_GOLD_RING = ${ring(T.GOLD_RING)};
`;
for (const [k, v] of [['TOWER_TOP', -1176], ['TOWER_GROUND', 336], ['TOWER_PLAY_TOP', -1156]]) if (T[k] !== v) throw new Error(`${k} changed`);
fs.writeFileSync(out, src);
console.log(`wrote ${path.relative(process.cwd(), out)}`);
