// STRUTHIO HANDHELD · generates core/struthio_rules.h from the arcade rulebook
// (arcade/src/data/rules.mjs): sim, scoring, lifecycle and input constants, the
// palette as RGB565, and the 5x7 font. The C core static-asserts its constants
// against this header, so a rules change that is not ported fails the build.
//   node handheld/tools/gen_rules.mjs
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';
import R from '../../arcade/src/data/rules.mjs';
const here = path.dirname(fileURLToPath(import.meta.url));
const rulesFile = path.join(here, '..', '..', 'arcade', 'src', 'data', 'rules.mjs');
const sha = crypto.createHash('sha256').update(fs.readFileSync(rulesFile)).digest('hex');
const snake = (k) => k.replace(/([a-z0-9])([A-Z])/g, '$1_$2').replace(/_Q(\d+)/, '_Q$1').toUpperCase();
const lines = [];
const def = (name, v) => lines.push(`#define ${name} ${v < 0 ? `(${v})` : v}`);
for (const [k, v] of Object.entries(R.sim)) if (Number.isInteger(v)) def(`STR_SIM_${snake(k)}`, v);
for (const [k, v] of Object.entries(R.lifecycle)) def(`STR_LIFECYCLE_${snake(k)}`, v);
for (const [k, v] of Object.entries(R.scoring)) if (Number.isInteger(v)) def(`STR_SCORING_${snake(k)}`, v);
R.scoring.eggChain.forEach((v, i) => def(`STR_SCORING_EGG_CHAIN_${i}`, v));
for (const [k, v] of Object.entries(R.scoring.joustClassBase)) def(`STR_SCORING_JOUST_${k}`, v);
def('STR_INPUT_CHORD_WINDOW_MS', R.input.chordWindowMs);
def('STR_INPUT_FLAP_BUFFER_TICKS', R.input.flapBufferTicks);
def('STR_INPUT_DART_ANGLE_DEGREES', R.input.dartAngleDegrees);
const rgb565 = (hex) => { const n = parseInt(hex.slice(1), 16); const r = n >> 16, g = (n >> 8) & 255, b = n & 255; return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3); };
const pal = Object.entries(R.palette);
const font = Object.entries(R.font_5x7);
const src = `// GENERATED by handheld/tools/gen_rules.mjs from arcade/src/data/rules.mjs. Do not edit.
// rules.mjs sha256 ${sha}
#pragma once
#include <stdint.h>

${lines.join('\n')}

// Palette (RGB565), in rules.mjs order.
enum {
${pal.map(([k], i) => `    STR_PAL_${snake(k)} = ${i},`).join('\n')}
    STR_PAL_COUNT = ${pal.length}
};
static const uint16_t STR_PALETTE_RGB565[STR_PAL_COUNT] = {
${pal.map(([k, v]) => `    0x${rgb565(v).toString(16).padStart(4, '0')}, /* ${k} ${v} */`).join('\n')}
};

// 5x7 font: 7 rows per glyph, bit 4 is the leftmost column.
typedef struct { char ch; uint8_t rows[7]; } str_glyph_t;
static const str_glyph_t STR_FONT_5X7[] = {
${font.map(([c, rows]) => `    {${JSON.stringify(c).replace(/^"|"$/g, "'").replace("'''", "'\\''")}, {${rows.join(', ')}}},`).join('\n')}
};
enum { STR_FONT_GLYPHS = ${font.length} };
`;
fs.writeFileSync(path.join(here, '..', 'core', 'struthio_rules.h'), src);
console.log('wrote core/struthio_rules.h');
