// STRUTHIO HANDHELD · generates audio/struthio_audio_data.h from the arcade's
// sound sources: the rulebook's audio block (arcade/src/data/rules.mjs: buses,
// event priorities and quantize, transport tempo), the synth voices and SFX
// table (arcade/src/audio/conductor.mjs, via its own synthConfig), and the music
// ducks in arcade/src/app/session.mjs. A change there that is not regenerated
// fails run_tests.sh.
//   node handheld/tools/gen_audio.mjs
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';
import R from '../../arcade/src/data/rules.mjs';
import { synthConfig } from '../../arcade/src/audio/conductor.mjs';
const here = path.dirname(fileURLToPath(import.meta.url));
const arcade = path.join(here, '..', '..', 'arcade');
const read = (f) => fs.readFileSync(path.join(arcade, f), 'utf8');
const sha = (f) => crypto.createHash('sha256').update(fs.readFileSync(path.join(arcade, f))).digest('hex');

// conductor.mjs keeps SFX, EVENT_TO_SFX and PROTECTED private: read the literals.
const conductor = read('src/audio/conductor.mjs');
const literal = (re) => { const m = conductor.match(re); if (!m) throw new Error('not found: ' + re); return new Function('return ' + m[1])(); };
const SFX = literal(/const SFX=Object\.freeze\((\{[\s\S]*?\n\})\);/);
const EVENT_TO_SFX = literal(/const EVENT_TO_SFX=(\{[^\n]*?\});/);
const PROTECTED = literal(/const PROTECTED=new Set\((\[[^\]]*\])\);/);

// session.mjs: music.duck({...}) after each event type; JOUST_CLASH only when the player is in it.
const session = read('src/app/session.mjs');
const DUCKS = [];
for (const m of session.matchAll(/if \(e\.type==='(\w+)'(&&\(e\.a===0\|\|e\.b===0\))?\)\{[^}]*?\n(?:[^\n]*\n){0,3}?if \(music\) music\.duck\((\{[^}]*\})\);/g)) {
  DUCKS.push({ type: m[1], playerOnly: !!m[2], ...new Function('return ' + m[3])() });
}
const gainMatch = session.match(/createMediaLoopTrack\(musicElement,\{gain:([\d.]+)/);
const sfxGainNode = session.match(/sfxGain\.gain\.value=([\d.]+)/);
const masterNode = session.match(/master\.gain\.value=([\d.]+)/);
const comp = {};
for (const k of ['threshold', 'knee', 'ratio', 'attack', 'release']) comp[k] = Number(session.match(new RegExp(`limiter\\.${k}\\.value=(-?[\\d.]+)`))[1]);
if (DUCKS.length < 4 || !gainMatch || !sfxGainNode || !masterNode) throw new Error('session.mjs audio wiring not recognised');

const cfg = synthConfig(R.audio);
const WAVES = ['SINE', 'TRIANGLE', 'SAW', 'PULSE_50', 'PULSE_25', 'PULSE_12_5', 'XORSHIFT_NOISE'];
const voiceIndex = Object.fromEntries(cfg.voices.map((v, i) => [v.id, i]));
const sfxKeys = Object.keys(SFX);
const QUANT = { NONE: 0, NEXT_EIGHTH: 1, NEXT_BEAT: 2 };
const evName = (t) => 'ST_EV_' + t;
const f = (x) => (Number.isInteger(x) ? x.toFixed(1) : String(x)) + 'f';

const src = `// GENERATED by handheld/tools/gen_audio.mjs. Do not edit.
// rules.mjs     sha256 ${sha('src/data/rules.mjs')}
// conductor.mjs sha256 ${sha('src/audio/conductor.mjs')}
// synth.mjs     sha256 ${sha('src/audio/synth.mjs')}
// session.mjs   sha256 ${sha('src/app/session.mjs')}
#pragma once
#include <stdint.h>
#include "struthio_core.h"

#define STA_SAMPLE_RATE ${R.audio.sampleRate}
#define STA_TRANSPORT_BPM_Q16 ${R.audio.transportBpmQ16}
#define STA_BEATS_PER_BAR ${R.audio.beatsPerBar}
// buses, after synthConfig (the SFX bus is scaled by 0.71 there)
#define STA_MASTER_GAIN_Q15 ${cfg.buses.masterGainQ15}
#define STA_MUSIC_GAIN_Q15 ${cfg.buses.musicGainQ15}
#define STA_SFX_GAIN_Q15 ${cfg.buses.sfxGainQ15}
#define STA_LIMITER_CEILING_Q15 ${cfg.buses.limiterCeilingQ15}
#define STA_DC_BLOCK_R_Q15 ${cfg.buses.dcBlockR_Q15}
#define STA_TRANSIENT_POOL_CAP ${cfg.buses.transientPoolCap}
#define STA_SUSTAINED_VOICE_CAP ${cfg.buses.sustainedVoiceCap}
// the WebAudio graph after the synth (session.mjs)
#define STA_SFX_NODE_GAIN ${f(Number(sfxGainNode[1]))}
#define STA_MASTER_NODE_GAIN ${f(Number(masterNode[1]))}
#define STA_COMP_THRESHOLD_DB ${f(comp.threshold)}
#define STA_COMP_KNEE_DB ${f(comp.knee)}
#define STA_COMP_RATIO ${f(comp.ratio)}
#define STA_COMP_ATTACK_S ${f(comp.attack)}
#define STA_COMP_RELEASE_S ${f(comp.release)}
#define STA_MUSIC_GAIN ${f(Number(gainMatch[1]))}

typedef enum { ${WAVES.map((w) => 'STA_WAVE_' + w).join(', ')} } sta_wave_t;
typedef enum { STA_FILTER_LP1, STA_FILTER_HP1 } sta_filter_t;
typedef struct { const char *id; uint8_t wave, filter; int32_t coef_q15, attack, decay, sustain_q15, release, gain_q15, glide; } sta_voice_t;
enum { STA_VOICE_COUNT = ${cfg.voices.length} };
static const sta_voice_t STA_VOICES[STA_VOICE_COUNT] = {
${cfg.voices.map((v) => `    {"${v.id}", STA_WAVE_${v.wave}, STA_FILTER_${v.filter}, ${v.coefQ15}, ${v.attack}, ${v.decay}, ${v.sustainQ15}, ${v.release}, ${v.gainQ15}, ${v.glide}},`).join('\n')}
};

typedef enum { STA_Q_NONE = 0, STA_Q_NEXT_EIGHTH = 1, STA_Q_NEXT_BEAT = 2 } sta_quantize_t;
// one row per SFX: voice, MIDI note, gate length (s), pitch jitter (semitones),
// minimum gap (s, 0 = none), priority and quantize (rules.mjs eventMap), protected
typedef struct { const char *key; uint8_t voice; int16_t midi; float len; int8_t jitter; float min_gap; uint8_t priority, quantize, protected_note; } sta_sfx_t;
enum { STA_SFX_COUNT = ${sfxKeys.length} };
static const sta_sfx_t STA_SFX[STA_SFX_COUNT] = {
${sfxKeys.map((k) => { const c = SFX[k], m = R.audio.eventMap[k]; return `    {"${k}", ${voiceIndex[c.voice]}, ${c.midi}, ${f(c.len)}, ${c.jitter || 0}, ${f(c.minGap || 0)}, ${m.priority}, ${QUANT[m.quantize]}, ${PROTECTED.includes(k) ? 1 : 0}},`; }).join('\n')}
};
// game event -> SFX row (-1: silent)
static inline int sta_sfx_for_event(int type) {
    switch (type) {
${Object.entries(EVENT_TO_SFX).map(([e, k]) => `    case ${evName(e)}: return ${sfxKeys.indexOf(k)};   // ${k}`).join('\n')}
    default: return -1;
    }
}

// music ducks (session.mjs): volume x (1 - (1 - depth) x 0.5) for attack + hold + release seconds
typedef struct { uint8_t event; uint8_t player_only; float depth, attack, hold, release; } sta_duck_t;
enum { STA_DUCK_COUNT = ${DUCKS.length} };
static const sta_duck_t STA_DUCKS[STA_DUCK_COUNT] = {
${DUCKS.map((d) => `    {${evName(d.type)}, ${d.playerOnly ? 1 : 0}, ${f(d.depth)}, ${f(d.attack)}, ${f(d.hold)}, ${f(d.release)}},`).join('\n')}
};
`;
const out = path.join(here, '..', 'audio', 'struthio_audio_data.h');
fs.mkdirSync(path.dirname(out), { recursive: true });
fs.writeFileSync(out, src);
console.log('wrote', path.relative(process.cwd(), out), `(${cfg.voices.length} voices, ${sfxKeys.length} sfx, ${DUCKS.length} ducks)`);
