// STRUTHIO HANDHELD · the port authority: SHA-256 of every browser source the
// C core is a port of. `--check` fails when the arcade simulation changes, so
// the port and the golden traces are never silently out of date.
//   node handheld/tools/port_authority.mjs           # write docs/PORT_AUTHORITY.md
//   node handheld/tools/port_authority.mjs --check
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';
const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(here, '..', '..');
const out = path.join(here, '..', 'docs', 'PORT_AUTHORITY.md');
const FILES = [
  ['arcade/src/data/rules.mjs', 'core/struthio_rules.h (generated), constants in core/struthio_sim.c'],
  ['arcade/src/core/fixed.mjs', 'core/struthio_sim.c (fixed-point helpers)'],
  ['arcade/src/core/rng.mjs', 'core/struthio_sim.c (xorshift32)'],
  ['arcade/src/core/canonical.mjs', 'core/struthio_digest.c'],
  ['arcade/src/core/sha256.mjs', 'core/struthio_digest.c'],
  ['arcade/src/sim/state.mjs', 'core/struthio_core.h, core/struthio_sim.c'],
  ['arcade/src/sim/world.mjs', 'core/struthio_sim.c'],
  ['arcade/src/sim/physics.mjs', 'core/struthio_sim.c'],
  ['arcade/src/sim/ai.mjs', 'core/struthio_sim.c'],
  ['arcade/src/sim/tower.mjs', 'core/struthio_tower.c (generated), core/struthio_sim.c'],
  ['arcade/src/sim/step.mjs', 'core/struthio_sim.c'],
  ['arcade/src/sim/game.mjs', 'core/struthio_digest.c (digest chain)'],
  ['arcade/src/input/input.mjs', 'core/struthio_input.c (InputNormalizer, wing path)'],
  ['arcade/src/app/session.mjs', 'canAcceptBufferedFlap, cleanup on death, restart on GAME OVER'],
  ['arcade/src/render/camera.mjs', 'render/struthio_greybox.c (presentation only)'],
];
const sha = (f) => crypto.createHash('sha256').update(fs.readFileSync(path.join(root, f))).digest('hex');
const version = (fs.readFileSync(path.join(root, 'arcade', 'index.html'), 'utf8').match(/STRUTHIO[^<]*?(\d+\.\d+\.\d+)/) || [])[1] || 'unknown';
const rows = FILES.map(([f, port]) => `| \`${f}\` | \`${sha(f)}\` | ${port} |`);
const md = `# STRUTHIO handheld · port authority

GENERATED by \`handheld/tools/port_authority.mjs\`. Do not edit.

The C core in \`handheld/core\` is a port of these browser sources of
**STRUTHIO ARCADE ${version}** (the repository's \`arcade/\`). The golden traces in
\`handheld/golden\` were recorded from them. If any hash changes, re-run the golden
exporter, port the change, and regenerate this file; \`--check\` (run by
\`handheld/run_tests.sh\`) fails until then.

| Source | SHA-256 | Ported as |
| --- | --- | --- |
${rows.join('\n')}

Notes

- Against the v0.4 package's 1.6.0 snapshot, \`rules.mjs\`, \`input.mjs\`,
  \`physics.mjs\`, \`ai.mjs\`, \`state.mjs\`, \`tower.mjs\` and \`world.mjs\` are
  byte-identical. Only \`step.mjs\` changed (1.7.0: rising straight up always
  wins a joust), which is why the port follows ${version}, not the 1.6.0 snapshot.
- Rendering, audio, PWA and save code are replaced on the device, not ported.
`;
if (process.argv.includes('--check')) {
  const same = fs.existsSync(out) && fs.readFileSync(out, 'utf8') === md;
  console.log(same ? 'PASS: port authority matches arcade sources' : 'FAIL: arcade sources changed since the port authority was written');
  process.exitCode = same ? 0 : 1;
} else {
  fs.writeFileSync(out, md);
  console.log(`wrote ${path.relative(process.cwd(), out)} (STRUTHIO ARCADE ${version})`);
}
