#pragma once
// Auto-snapshotted from STRUTHIO ARCADE 1.6.0 src/data/rules.mjs.
// Treat as port-authority constants; do not tune on ESP until golden replay passes.

#define STRUTHIO_TICK_HZ 60
#define STRUTHIO_SUBPIXELS_PER_PIXEL 256
#define STRUTHIO_LOGICAL_W 256
#define STRUTHIO_LOGICAL_H 384
#define STRUTHIO_GRAVITY_SUBPX_TICK2 21
#define STRUTHIO_FLAP_IMPULSE_SUBPX_TICK 333
#define STRUTHIO_FLAP_VY_CLAMP -640
#define STRUTHIO_MAX_AIR_SPEED 444
#define STRUTHIO_MAX_GROUND_SPEED 393
#define STRUTHIO_MAX_FALL 896
#define STRUTHIO_GROUND_ACCEL 18
#define STRUTHIO_AIR_ACCEL 15
#define STRUTHIO_GROUND_FRICTION 14
#define STRUTHIO_AIR_DRAG 2
#define STRUTHIO_WING_MAX 64
#define STRUTHIO_CHORD_WINDOW_MS 100
#define STRUTHIO_FLAP_BUFFER_TICKS 8
#define STRUTHIO_DART_ANGLE_DEGREES 35
#define STRUTHIO_LIFECYCLE_EGG_TICKS 360
#define STRUTHIO_LIFECYCLE_HATCHING_TICKS 60
#define STRUTHIO_LIFECYCLE_REMOUNTING_TICKS 90
