// STRUTHIO ARCADE service worker: precache every file of the build, then
// serve them offline. Generated by tools/build.py; do not edit the list.
const BUILD='STRUTHIO-ARCADE-1.3.2';
const CACHE=`struthio-arcade-${BUILD}`;
const CORE=["./", "./index.html", "./manifest.webmanifest", "./assets/arcade-frame.css", "./assets/arcade.css", "./assets/art/background-near.webp", "./assets/art/background-rear.webp", "./assets/art/hero-art.webp", "./assets/art/islands.json", "./assets/art/islands.webp", "./assets/art/jousters.webp", "./assets/art/share-card.jpg", "./assets/audio/tarmac-at-midnight-loop.mp3", "./assets/icons/apple-touch-icon.png", "./assets/icons/icon-192.png", "./assets/icons/icon-512.png", "./src/app/art.mjs", "./src/app/boot.mjs", "./src/app/feel.mjs", "./src/app/session.mjs", "./src/audio/conductor.mjs", "./src/audio/music.mjs", "./src/audio/stereo.mjs", "./src/audio/synth.mjs", "./src/audio/worklet.mjs", "./src/core/canonical.mjs", "./src/core/fixed.mjs", "./src/core/rng.mjs", "./src/core/sha256.mjs", "./src/data/rules.mjs", "./src/input/input.mjs", "./src/render/atlas.mjs", "./src/render/bird-animation.mjs", "./src/render/bird-inks.mjs", "./src/render/camera.mjs", "./src/render/grade.mjs", "./src/render/islands.mjs", "./src/render/props.mjs", "./src/render/renderer.mjs", "./src/render/ring-fx.mjs", "./src/render/scene.mjs", "./src/render/sprites.mjs", "./src/render/surface.mjs", "./src/render/visual-spec.mjs", "./src/save/checkpoint.mjs", "./src/save/save-schema.mjs", "./src/save/schema.mjs", "./src/sim/ai.mjs", "./src/sim/game.mjs", "./src/sim/physics.mjs", "./src/sim/state.mjs", "./src/sim/step.mjs", "./src/sim/tower.mjs", "./src/sim/world.mjs", "./src/ui/controls.mjs", "./src/ui/hud.mjs", "./src/ui/pwa.mjs", "./src/ui/viewport-shim.mjs"];
self.addEventListener('install',(event)=>event.waitUntil((async()=>{
const cache=await caches.open(CACHE);
try{for (const url of CORE){const r=await fetch(url,{cache:'reload'});if (!r.ok) throw new Error(`precache ${url} ${r.status}`);await cache.put(url,r);}}
catch (error){await caches.delete(CACHE);throw error;}
})()));
self.addEventListener('activate',(event)=>event.waitUntil((async()=>{
for (const name of await caches.keys()) if (name!==CACHE&&name.startsWith('struthio-arcade-')) await caches.delete(name);
await self.clients.claim();
})()));
self.addEventListener('message',(event)=>{if (event.data?.type==='SKIP_WAITING') self.skipWaiting();});
self.addEventListener('fetch',(event)=>{
if (event.request.method!=='GET'||new URL(event.request.url).origin!==location.origin) return;
event.respondWith((async()=>{
const cache=await caches.open(CACHE);
if (event.request.mode==='navigate'){const hit=await cache.match('./index.html');return hit||fetch(event.request);}
const hit=await cache.match(event.request,{ignoreSearch:true});
if (hit){
const range=event.request.headers.get('range');
if (!range) return hit;
const body=await hit.arrayBuffer(),m=/bytes=(\d*)-(\d*)/.exec(range)||[];
const start=Number(m[1]||0),end=m[2]?Math.min(Number(m[2]),body.byteLength-1):body.byteLength-1;
return new Response(body.slice(start,end+1),{status:206,headers:{'content-type':hit.headers.get('content-type')||'application/octet-stream','content-range':`bytes ${start}-${end}/${body.byteLength}`,'accept-ranges':'bytes'}});
}
const response=await fetch(event.request);
if (response.ok&&response.status===200) cache.put(event.request,response.clone()).catch(()=>{});
return response;
})());
});
